#pragma once

enum class SoundAsset {
    BOING,
    PLAYER_1_HAS_THE_WIENER,
    PLAYER_2_HAS_THE_WIENER,
    PLAYER_3_HAS_THE_WIENER,
    PLAYER_4_HAS_THE_WIENER,
    CHEERING,
    SQUISH,
    DRILL,
    DOG_LAPPING_WATER,
    BRIGHT,
    MALFUNCTIONING_STATIC
};
